[tool.black]
line-length = 120
target-version = ['py38']
skip-string-normalization = true
safe = true

[tool.isort]
profile = "black"
py_version = 38
line_length = 120
skip_gitignore = true

[tool.pylint.messages_control]
max-line-length = 120

[tool.ruff]
line-length = 120
